# This is a TOML configuration file for market_miner.py

[miners]

    [miners.StockCluster]

    [miners.DailyOHLC]
        filename = "<select-path>/daily_ohlc.py"
        # to follow specific symbols
        # symbols = ['SPY',]

        days = 60

        min_price = 2.0
        max_price = 20.0


